### ISSUE TITLE
Open discussions about the future of this software

### ISSUE THREAD

**Issue by ron-from-nl** [MatMoul/g810-led#1]
Hi MatMoul,

Thank you for all the work on g810-led, now i can color my keys under Linux.
There some minor improvements i added to your installation and script:

Make sure pyusb 1.0.0 is installed
apt-get install python-pip
pip install pyusb # (PyUSB-1.0.0.tar.gz) pyusb has to be version 1.0.0

further i added 1 mSec delay (2 extra lines of code) in method "setKeyColorInternal(..)" to give     dev.ctrl_transfer(0x21,0x09,0x0211,1,data) some time to finish the LED update

so summarizing in the import section only a:
```
from time import sleep
```
and the following line to method: setKeyColorInternal
```
sleep(0.001)
```

Here is the exact location where I put the **sleep** in the setKeyColorInternal method:

```
def setKeyColorInternal(base, key, color, ext):

  global dev

  try:

    data = base+key+color+'0000000000000000'

    if ext is True:

      data = data + '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'

    data = [ int(''.join([data[i], data[i+1]]), base=16) for i in range(0, len(data), 2)]

    dev.ctrl_transfer(0x21,0x09,0x0211,1,data)

    sleep(0.001)

  except:

    print 'Error setting color: key=' + key + " color=" + color
```

Now all keyboard-leds are consistently updated all at once

Thanks again MatMoul :)

Kind regards, Ron

**Comment by MatMoul** [comment]
Thanks for your return...

This issue will be reserved for discussion on the futur on this soft.

As I indicated, this is a first shot with only 12H of code.

I expect some problems with different keyboard layout, missed config (such as timeouts) and other ...

After this retro engineering with Python and Wireshark, I hope to pass the code in C ++ for his performance ...
I already work on it but return are welcome.

**Comment by MatMoul** [comment]
@ron-from-nl : If you want to add your change, fork and pull back your changes...
I will create a C++ version but the Python version will remain available ...

**Comment by ron-from-nl** [comment]
I forked and created a pull request with a small fix for the above issue.

Cheers, Ron
