### ISSUE TITLE
g610: Matching or compatible device not found error

### ISSUE THREAD

**Issue by 0xMatt** [MatMoul/g810-led#111]
I'm not able to set anything due to this error. I checked --list-keyboards and it is indeed found.

```g610-led --list-keyboards
Device: Logitech - Gaming Keyboard G610
	Vendor ID: 046d
	Product ID: c338
	Serial Number: 0B8F36713135
```

If any additional information is needed let me know and I'll get that for you, thanks.

**Comment by MatMoul** [comment]
it seem you have found a new Product ID : c338.
If you want to make a PR, look at line 30 to 41 of src/classes/Keyboard.h

**Comment by 0xMatt** [comment]
Sorry, I meant to update this after I got it working. It seems all I needed was to reboot. After doing so it worked just fine. Thanks for your time!

**Comment by danielamorais** [comment]
The same happened to me and worked after rebooting, thanks!

ID 046d:c338 Logitech, Inc. Gaming Keyboard G610
OS: Fedora 30
