### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by Dobeedoo** [MatMoul/g810-led#120]
THANKS for a truly great driver, its excellent!

However, I have not yet found a way to set brightness? It would help with brightness in the simplest manner, ie same for all keys, if that is easier to implement. I mainly use the keyboard as an aid, to actually see the keys. I don't know C or C++, but some Python, so is there anything I can do to help, just ask.
./Doobedoo

**Comment by smasty** [comment]
You can control the brightness with the color value. For example, `FF0000` is the brightest red, while `800000` is somewhere in the middle.

**Comment by Dobeedoo** [comment]
Awesome! Thanks
