### ISSUE TITLE
Loading a profile

### ISSUE THREAD

**Issue by sigmoidx** [MatMoul/g810-led#129]
Hello?

I have a question about loading a profile. Since there is an option for loading a profile in this repository, I wonder it also can load the profile file made in Windows 10. 

BTW, the keyboard I'm using is Logitech G Pro keyboard.

Thanks,

**Comment by MatMoul** [comment]
Sorry, profile files for g810-led aren't the same as windows...

**Comment by nikhilsuvarna89** [comment]
what  file format should be the profile ?
