### ISSUE TITLE
List of keys in --help

### ISSUE THREAD

**Issue by ShadauxCat** [MatMoul/g810-led#13]
I had to examine source code to determine that I needed to type `openbracket` and `closebracket` to get the `[` and `]` keys to change, since `[` and `]` are not accepted as values. It would be very helpful to list the valid key identifiers in `--help`.

**Comment by MatMoul** [comment]
Need Time...

**Comment by ShadauxCat** [comment]
If I get time this weekend I may create a PR addressing all the issues I've opened.

**Comment by MatMoul** [comment]
PR is open ;.p

**Comment by MatMoul** [comment]
PR is close for this issue.
Now include in the "keynames" branch

**Comment by larsnaesbye** [comment]
Nice! Shouldn't it get merged into the main branch? :-)

**Comment by MatMoul** [comment]
Branch merged
