### ISSUE TITLE
G900 Mouse

### ISSUE THREAD

**Issue by s3v3nh4cks** [MatMoul/g810-led#130]
Any possibility of getting your script to work with the G900 Optical mouse?? It is the matching Mouse to the G910 Keyboard (which your script works great on)

**Comment by MatMoul** [comment]
This is a very hard work to maintain this software for keyboards...
I've a pull request #106 for the G403 mouse from more than 6 months...
If you want to contribute, your welcome...

**Comment by MatMoul** [comment]
Sorry, mouse can not suported now
