### ISSUE TITLE
G910 Orion Spectrum Ubuntu 18.04 Windows/Super Key stops working

### ISSUE THREAD

**Issue by tosaddler** [MatMoul/g810-led#132]
Running `xev` the input presses aren't even detected. Persists even after trying to uninstall. Not really sure what else I can do to troubleshoot this problem. Any help would be greatly appreciated.

**Comment by MatMoul** [comment]
Sorry but no problem here...
Do you have tested your keyboard on an a dual boot or on an other computer?

**Comment by tosaddler** [comment]
So for anyone who stumbles upon this problem in the future...

Did you know that the G910 has a Game/Windows button? It's at the top of the keyboard next to the Num/Caps/Scroll lights. If you're like me and never used it, apparently it disables the Windows/Super buttons as well as the menu button next to RCtrl.

Somehow that button activated after installing g910-led. So pressing it again should fix your problems. I feel silly but I just have never had the issue of needing to lock the Super/Windows key while gaming so I never used that button.
