### ISSUE TITLE
matching or compatible device not found? g413

### ISSUE THREAD

**Issue by tofuhead** [MatMoul/g810-led#135]
hi, I get this error with Logitechj G413... which should be supported?

./g810-led --list-keyboards                                                                                                         10:32
Device: Logitech - G413 Carbon Mechanical Gaming Keyboard
        Vendor ID: 046d
        Product ID: c33a
        Serial Number: 167F37713432

./g810-led -k w ff0000                                                                                                              10:36
Matching or compatible device not found !

no matter what commands I try it's always the same.

.b

**Comment by MatMoul** [comment]
use g810-led as root
or add the udev rules...
