### ISSUE TITLE
Can't turn the LED on, I have g413 carbon

### ISSUE THREAD

**Issue by tgautam03** [MatMoul/g810-led#154]
LED had the breathing effect by default but as I rebooted, it just stopped and now I can't get the LED back on.

**Comment by MatMoul** [comment]
Not sure what's the problem but g810-led has a service that set all keys to off when you reboot.
This prevent the keyboard to flash 2 or 3 time at boot...
On the boot the profile are loaded by the udev rules.
Do you have copied the file in /etc/udev/rules.d/ ?
You can make a test with `g413-led -a 00ff00`
If your keyboard is not found, try with sudo.
If this work with sudo, you have a problem with the udev rules
