### ISSUE TITLE
Set effect period in milliseconds

### ISSUE THREAD

**Issue by DanEble** [MatMoul/g810-led#156]
Experimenting with a G Pro, I have found that the USB command to set the breathing, cycle, and wave effects includes the period in milliseconds as a 16-bit number.  The current implementation of "speed" sets the high byte of this value, so its resolution is 256ms.

I would like to contribute a change taking advantage of this discovery, but first I would like to receive approval for the UI syntax to use.  My suggestion is to leave the 2-digit hexadecimal option alone and add support for these two alternatives:
* a base-10 integer followed immediately by "s" (no space between) for a value in seconds
* a base-10 integer followed immediately by "ms" (no space between) for a value in milliseconds

I also suggest changing the term "speed" in the usage text to "period" or "cycle duration."

Finally, I would like to know if it is acceptable to use std::chrono::duration in this project.  Thanks.

**Comment by MatMoul** [comment]
This can be done but I've some remarks...

Adding support for s or ms is part of the UI and need to be writed outside of Keyboard.cpp
You can use helpers and the main.cpp

And for std::chrono, it's possible but test your code before and after with `time g810-lef -p /etc/g810-led/profile`
On my computer it take ~60ms
