### ISSUE TITLE
G Pro - scroll lock  no lit indicator

### ISSUE THREAD

**Issue by giostark** [MatMoul/g810-led#164]
Hi,
Im facing to configure my profile .
All the keys work well and i can configure them all.
Just the indicator of the Scroll Lock key do not want lit after i press the key.
Im running the last Arch version 0.3.1-1
https://aur.archlinux.org/packages/g810-led-git/
The lit work properly under windows and before the module is started.
The CapsLock key if pressed return the right lit so the problem concern just the Scroll key.
Under windows is possible customize the lit and the the two buttons (back light and win lock) separately .
There is a way to do that here too?
Any suggestion or solution? 
Many thanks!

Sergio

**Comment by MatMoul** [comment]
Try it on TTY...
It's a bad config on Xorg

**Comment by giostark** [comment]
Thanks for quick answer!
You are right. Under TTY work fine. 
Of course is not strictly necessary this light. 
By the way... When you say is a "bad config  on Xorg" , do you know also where to put hands for solve it, or a direction where investigate? Or is too complicated?
I already appreciate so much your work ! 
If is a mess  I dont want waste your time :-)

**Comment by MatMoul** [comment]
I had sought a solution to this problem but I lost my documentation because I did not use this key ...
From memory, it must be the keyboard config for Xorg:
/etc/X11/xorg.conf.d/00-keyboard.conf
or can be xmodmap
