### ISSUE TITLE
G213 not working

### ISSUE THREAD

**Issue by fentas** [MatMoul/g810-led#166]
Hello,
thanks for the repo :+1: 
Got a new G213 but it seems to have some complications.

```shell
➜ lsusb
[...]
Bus 001 Device 058: ID 046d:c336 Logitech, Inc.
[...]

➜ g213-led --list-keyboards
Device: Logitech - Gaming Keyboard G213
        Vendor ID: 046d
        Product ID: c336
        Serial Number: 0A7638713836

➜ g213-led --print-device
Matching or compatible device not found !
```

Please let me know if you need more information.

**Comment by MatMoul** [comment]
Try with sudo...
If this work, you need to add the udev rules to use it as user

**Comment by fentas** [comment]
:sweat_smile: did the trick. Thanks for the quick response! Keep it up. :+1:
