### ISSUE TITLE
Developing for other brands

### ISSUE THREAD

**Issue by marsupialsoup** [MatMoul/g810-led#168]
Hello, I would like to develop a similar controller for certain Redragon keyboards. Could anyone point to how one might get started on this? 

This is a little off topic here, I am trying to understand the code, or trying to find a way to do so.

**Comment by MatMoul** [comment]
Look at https://github.com/MatMoul/g810-led-python
This is the first project that I made in python (it's more easy for test).
I used Wireshark for reading USB data
