### ISSUE TITLE
Can get single key or groups to animate?

### ISSUE THREAD

**Issue by msagerup** [MatMoul/g810-led#172]
I am trying to follow along with the help text. I manage to set colors. 
But I am trying to play with the -fx.
The sample works when I enter it. 
This works:
sudo g513-led -fx vwave keys 0a 

But if i want to change it from "keys" to . i.e "fkeys" i dosent work
This does not work: 
sudo g513-led -fx vwave fkeys 0a

**Comment by MatMoul** [comment]
Possible value for -fx are all, keys and logo...
These values are specified in `g810-led --help-effects`
The -fx arg use the internal animations of the keyboard and it has only two region (keys and logo)
