### ISSUE TITLE
Can't "Include in implementing source files"

### ISSUE THREAD

**Issue by Zholaman** [MatMoul/g810-led#173]
Hi,
I tried to follow the instruction posted here but no success.

lsusb issued:
Bus 001 Device 003: ID 046d:c331 Logitech, Inc.

What I need to do next. I don't understood this part:
"Building and linking against the libg810-led library :
Include in implementing source files.
#include <g810-led/Keyboard.h>
To link, simply provide -lg810-led to the build flags.
To build the g810-led application as a dynamically-linked variant, run the target:
make bin-linked
"
I do not know what file and where I need to edit and include to it "#include <g810-led/Keyboard.h>" and etc.

So can I ask you to provide more details in step by step manner.

Thanks a lot!

**Comment by MatMoul** [comment]
Hi,

`make bin-linked` is only for developers that want make her own binary...
For a simple use, you can skip this part...
