### ISSUE TITLE
Solus

### ISSUE THREAD

**Issue by habj89** [MatMoul/g810-led#180]
I have not tried yet, but I wounder if this will work on solus?

**Comment by MatMoul** [comment]
@habj89 Looking at https://repology.org/project/g810-led/versions ...
It seem that a package is available...
I've not tested but try it and give feedback...

**Comment by Krutonium** [comment]
I'm currently using it on Solus. `eopkg install g810-led`

**Comment by MatMoul** [comment]
@Krutonium Thanks to confirm that the Solus package work and the PR #184 ...

@habj89 I close the issue but you can reopen it if it isn't resolved for you.
