### ISSUE TITLE
g213-led how to save profile in Ubuntu 19-04

### ISSUE THREAD

**Issue by franko46** [MatMoul/g810-led#189]
I am using g213 version 0.3.3 to successfully configure the colors on my G 213 keyboard but I cannot understand how to save the profile so that it starts automatically when I next start my computer. I cannot see any reference in the help file.

**Comment by MatMoul** [comment]
The magic file is `/etc/g810-led/profile`
https://github.com/MatMoul/g810-led/blob/master/INSTALL.md#boot-profiles-

**Comment by franko46** [comment]
Thanks Mat,
With you pointing me in the correct direction it is working well on reboot. Now I just need to find the best color combinations!
Best wishes , Franko46
