### ISSUE TITLE
Ubuntu/Debian version

### ISSUE THREAD

**Issue by johnmanko** [MatMoul/g810-led#209]
It seems that the debian version is a few versions behind. 

```
$ g810-led
g810-led
--------
Version : 0.3.3
```

Are you the maintainer for that package?

**Comment by MatMoul** [comment]
I'm not the maintainer of the Debian version.
But Debian take time to provide new version in the current release.
You can see on this page that debian testing has the 0.3.9 :
https://repology.org/project/g810-led/versions
