### ISSUE TITLE
sometimes on boot or waking from sleep they leds cycle serveral times

### ISSUE THREAD

**Issue by jgslade** [MatMoul/g810-led#213]
Sometimes when booting up or waking from sleep the leds will cycle from off to the rainbow wave to my chosen profiles several times, while it's doing this cycling I cannot use the keyboard. 

> [ 2381.844326] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0009/input/input43
[ 2381.898440] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0009/input/input44
[ 2381.898684] hid-generic 0003:046D:C335.0009: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2382.005006] audit: type=1130 audit(1583166733.670:137): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-suspend comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2382.005012] audit: type=1131 audit(1583166733.670:138): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-suspend comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2382.009411] Generic FE-GE Realtek PHY r8169-300:00: attached PHY driver [Generic FE-GE Realtek PHY] (mii_bus:phy_addr=r8169-300:00, irq=IGNORE)
[ 2382.122710] r8169 0000:03:00.0 enp3s0: Link is Down
[ 2383.020023] usb 3-1.1: USB disconnect, device number 7
[ 2383.391476] usb 3-1.1: new full-speed USB device number 8 using xhci_hcd
[ 2383.505527] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2383.505530] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2383.505531] usb 3-1.1: Product: Gaming Keyboard G910
[ 2383.505532] usb 3-1.1: Manufacturer: Logitech
[ 2383.505533] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2383.598959] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.000A/input/input47
[ 2383.655106] hid-generic 0003:046D:C335.000A: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2383.658145] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000B/input/input48
[ 2383.714882] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000B/input/input49
[ 2383.714965] hid-generic 0003:046D:C335.000B: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2385.835653] usb 3-1.1: USB disconnect, device number 8
[ 2386.006823] r8169 0000:03:00.0 enp3s0: Link is Up - 1Gbps/Full - flow control rx/tx
[ 2386.006835] IPv6: ADDRCONF(NETDEV_CHANGE): enp3s0: link becomes ready
[ 2386.161331] usb 3-1.1: new full-speed USB device number 9 using xhci_hcd
[ 2386.275283] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2386.275288] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2386.275291] usb 3-1.1: Product: Gaming Keyboard G910
[ 2386.275293] usb 3-1.1: Manufacturer: Logitech
[ 2386.275295] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2386.351134] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.000C/input/input52
[ 2386.405092] hid-generic 0003:046D:C335.000C: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2386.407827] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000D/input/input53
[ 2386.464737] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000D/input/input54
[ 2386.465056] hid-generic 0003:046D:C335.000D: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2388.025536] audit: type=1130 audit(1583166739.690:139): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2388.381281] audit: type=1130 audit(1583166740.047:140): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ntpd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2388.395652] usb 3-1.1: USB disconnect, device number 9
[ 2388.734513] usb 3-1.1: new full-speed USB device number 10 using xhci_hcd
[ 2388.842527] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2388.842530] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2388.842531] usb 3-1.1: Product: Gaming Keyboard G910
[ 2388.842532] usb 3-1.1: Manufacturer: Logitech
[ 2388.842533] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2388.908270] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.000E/input/input57
[ 2388.964659] hid-generic 0003:046D:C335.000E: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2388.965600] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000F/input/input58
[ 2389.021304] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.000F/input/input59
[ 2389.021467] hid-generic 0003:046D:C335.000F: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2390.699243] usb 3-1.1: USB disconnect, device number 10
[ 2391.054372] usb 3-1.1: new full-speed USB device number 11 using xhci_hcd
[ 2391.162492] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2391.162496] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2391.162499] usb 3-1.1: Product: Gaming Keyboard G910
[ 2391.162501] usb 3-1.1: Manufacturer: Logitech
[ 2391.162503] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2391.243953] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.0010/input/input62
[ 2391.297799] hid-generic 0003:046D:C335.0010: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2391.298953] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0011/input/input63
[ 2391.354559] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0011/input/input64
[ 2391.354664] hid-generic 0003:046D:C335.0011: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2393.259237] usb 3-1.1: USB disconnect, device number 11
[ 2393.610886] usb 3-1.1: new full-speed USB device number 12 using xhci_hcd
[ 2393.718904] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2393.718906] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2393.718907] usb 3-1.1: Product: Gaming Keyboard G910
[ 2393.718908] usb 3-1.1: Manufacturer: Logitech
[ 2393.718909] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2393.804293] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.0012/input/input67
[ 2393.860998] hid-generic 0003:046D:C335.0012: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2393.861900] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0013/input/input68
[ 2393.917728] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0013/input/input69
[ 2393.917883] hid-generic 0003:046D:C335.0013: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2395.819250] usb 3-1.1: USB disconnect, device number 12
[ 2396.204025] usb 3-1.1: new full-speed USB device number 13 using xhci_hcd
[ 2396.312019] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2396.312023] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2396.312026] usb 3-1.1: Product: Gaming Keyboard G910
[ 2396.312028] usb 3-1.1: Manufacturer: Logitech
[ 2396.312030] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2396.396224] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.0014/input/input72
[ 2396.450853] hid-generic 0003:046D:C335.0014: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2396.451744] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0015/input/input73
[ 2396.507414] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0015/input/input74
[ 2396.507495] hid-generic 0003:046D:C335.0015: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2398.379251] usb 3-1.1: USB disconnect, device number 13
[ 2398.730572] usb 3-1.1: new full-speed USB device number 14 using xhci_hcd
[ 2398.845479] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2398.845481] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2398.845483] usb 3-1.1: Product: Gaming Keyboard G910
[ 2398.845484] usb 3-1.1: Manufacturer: Logitech
[ 2398.845485] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2398.846242] audit: type=1131 audit(1583166750.511:141): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2398.924367] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.0016/input/input77
[ 2398.980708] hid-generic 0003:046D:C335.0016: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2398.981603] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0017/input/input78
[ 2399.037334] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0017/input/input79
[ 2399.037498] hid-generic 0003:046D:C335.0017: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2400.939240] usb 3-1.1: USB disconnect, device number 14
[ 2400.939319] g910-led[32164]: segfault at 0 ip 00007fabd44d31e5 sp 00007ffe6155d918 error 4 in libc-2.31.so[7fabd4397000+14c000]
[ 2400.939331] Code: 00 00 0f 1f 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1
[ 2400.939368] audit: type=1701 audit(1583166752.604:142): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=32164 comm="g910-led" exe="/usr/bin/g810-led" sig=11 res=1
[ 2400.948454] audit: type=1334 audit(1583166752.614:143): prog-id=15 op=LOAD
[ 2400.948618] audit: type=1334 audit(1583166752.614:144): prog-id=16 op=LOAD
[ 2400.949337] audit: type=1130 audit(1583166752.614:145): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-32184-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2401.290379] usb 3-1.1: new full-speed USB device number 15 using xhci_hcd
[ 2401.398417] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2401.398421] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2401.398424] usb 3-1.1: Product: Gaming Keyboard G910
[ 2401.398426] usb 3-1.1: Manufacturer: Logitech
[ 2401.398428] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2401.483978] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.0018/input/input82
[ 2401.540645] hid-generic 0003:046D:C335.0018: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2401.541515] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0019/input/input83
[ 2401.597116] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.0019/input/input84
[ 2401.597232] hid-generic 0003:046D:C335.0019: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2421.842340] audit: type=1131 audit(1583166773.505:146): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-32184-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2422.010024] audit: type=1334 audit(1583166773.675:147): prog-id=16 op=UNLOAD
[ 2422.010031] audit: type=1334 audit(1583166773.675:148): prog-id=15 op=UNLOAD
[ 2423.467246] usb 3-1.1: USB disconnect, device number 15
[ 2423.815627] usb 3-1.1: new full-speed USB device number 16 using xhci_hcd
[ 2423.927020] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2423.927022] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2423.927024] usb 3-1.1: Product: Gaming Keyboard G910
[ 2423.927025] usb 3-1.1: Manufacturer: Logitech
[ 2423.927026] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2424.012006] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.001A/input/input87
[ 2424.065769] hid-generic 0003:046D:C335.001A: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2424.066637] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.001B/input/input88
[ 2424.125691] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.001B/input/input89
[ 2424.125771] hid-generic 0003:046D:C335.001B: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1
[ 2426.027244] usb 3-1.1: USB disconnect, device number 16
[ 2426.378813] usb 3-1.1: new full-speed USB device number 17 using xhci_hcd
[ 2426.486837] usb 3-1.1: New USB device found, idVendor=046d, idProduct=c335, bcdDevice= 6.02
[ 2426.486841] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2426.486844] usb 3-1.1: Product: Gaming Keyboard G910
[ 2426.486846] usb 3-1.1: Manufacturer: Logitech
[ 2426.486848] usb 3-1.1: SerialNumber: 0C6E384D3833
[ 2426.571950] input: Logitech Gaming Keyboard G910 as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.0/0003:046D:C335.001C/input/input92
[ 2426.625727] hid-generic 0003:046D:C335.001C: input,hidraw0: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input0
[ 2426.626923] input: Logitech Gaming Keyboard G910 Keyboard as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.001D/input/input93
[ 2426.682247] input: Logitech Gaming Keyboard G910 Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb3/3-1/3-1.1/3-1.1:1.1/0003:046D:C335.001D/input/input94
[ 2426.682407] hid-generic 0003:046D:C335.001D: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:0c:00.3-1.1/input1

**Comment by MatMoul** [comment]
I don't want to read all these lines...
Firstly, 
What's your OS and version?
What's your g810-led version?
You do you have installed g810-led?

**Comment by jgslade** [comment]
I am using Manjaro, I installed it from the AUR.

**Comment by MatMoul** [comment]
Ok, I maintain the AUR package, it's installed same as me...
Your two lines of explain seem a systemd unit config issue...
I suggest you delete g810-led-git and see if you experience the same nonresponse problem on startup.

**Comment by jgslade** [comment]
If I uninstall g810-led-git it does boot normally and it keeps the last profile that was loaded. Though we did last power for a few hours there either day and the profile reset to the default and I had to reinstall to change the profile again.

If I disable the systemd until it still had problems on reboot.

**Comment by MatMoul** [comment]
Your case is very strange, g810-led is called by udev when you connect or boot your computer.
g810-led take normally ~ 100ms.
If it is run multiple time, it's an external call.

**Comment by jgslade** [comment]
Very interesting...
I'll check my system but I don't recall doing any manual calls. 😕

**Comment by MatMoul** [comment]
Some ideas :
- Use of a USB hub
- Bad USB connection

Your issue seem a connect/disconnect case.

**Comment by jgslade** [comment]
It is plugged into a USB hub. I'll plug it into it's own port and see if that resolves it.

**Comment by jgslade** [comment]
That did it. Plugging the keyboard into it's own slot on the computer let to a successful bit sequence.

**Comment by jgslade** [comment]
Plugging the keyboard in directly to the computer and reinstalling g810-leds seems to have fixed the issue. I'll need to do a few more boots to make sure.

**Comment by jgslade** [comment]
I've had several successful boots since plugging the keyboard directly into the PC rather than through a hub.

**Comment by d43m0nhLInt3r** [comment]
same issue here. I use Manjaro Gnome and installed the AUR package. I dont use a hub and the issue happen on every usb port.
