### ISSUE TITLE
Sponsoring features?

### ISSUE THREAD

**Issue by GabrieleCacchioni** [MatMoul/g810-led#221]
Hi, is there a way to sponsor features/enhancements?
I'd like to have support for the G915 and would't mind to make a donation to speed it up

**Comment by MatMoul** [comment]
Thanks, you can support me on this page : https://matmoul.ch/supportme
But it doesn't speed anything, I work on my projects when I'm motivated and my brain is free...

**Comment by Elijas** [comment]
@GabrieleCacchioni Same. https://github.com/MatMoul/g810-led/issues/198#issuecomment-692610351 @yawor Is working on the G915 with some progress, we could ask him
