### ISSUE TITLE
FN inversion?

### ISSUE THREAD

**Issue by nickberry17** [MatMoul/g810-led#232]
Hi,

Really like the driver, thanks! Question: is there any way to invert the FN key for just the PRTSC, SCRLK and PAUSE buttons so I can use them as volume control without pressing FN?  If it matters, I am using a G512 Carbon.

**Comment by MatMoul** [comment]
Hi, g810-led can only set led on the keyboard...
It's not taked to be a key interceptor...

**Comment by nickberry17** [comment]
OK, thanks for clarifying
