### ISSUE TITLE
G213 Prodigy

### ISSUE THREAD

**Issue by jerome-diver** [MatMoul/g810-led#246]
Thank you for share your code.
I read your source code and see that for G213, user can only use region and all keys colors, and effects for all.

## My question is:
is it a technical limitation of the keyboard to not be possible to use any simple keys (and so, any group of keys) ? (or the source code has not been made actually ?)

**Comment by pearsonk** [comment]
The G213 only has 5 zones of lighting, not an LED per key. This is reflected in the specs from the Logitech site:
https://www.logitechg.com/en-us/products/gaming-keyboards/g213-rgb-gaming-keyboard.920-008083.html#product-tech-specs
