### ISSUE TITLE
[G213] I already connected a G213 to my PC but it isn't detected by g213-led.

### ISSUE THREAD

**Issue by naoya0x00** [MatMoul/g810-led#248]
#### `$ g213-led --list-keyboards`
``` console
Device: Logitech - Gaming Keyboard G213
	Vendor ID: 046d
	Product ID: c336
	Serial Number: 156938653235
```

#### `$ g213-led -a 5B01FA`
``` console
Matching or compatible device not found !
```

### environments
OS: Ubuntu20.04
g213-led: v0.3.9

**Comment by piozylka** [comment]
same problem 
BUMP

**Comment by piozylka** [comment]
> same problem
> BUMP

ahhh when i run: 
`sudo g213-led -a 00ff00` it works
so its the privileges problem

**Comment by naoya0x00** [comment]
It worked on my PC, too. Thank you for your answer!
