### ISSUE TITLE
Error: Can not write to hidraw, try with the libusb version

### ISSUE THREAD

**Issue by SafetyFast** [MatMoul/g810-led#265]
I've been using g810-led to control a g213 keyboard on Ubuntu 20.04 for some time with no issues.  Today, however, I get the error regarding hidraw.  I'm assuming this is in response to some system updates installed yesterday.

Sorry if I'm being dense, but, how do 'try with the libusb version?'  

Thanks!

**Comment by SafetyFast** [comment]
Sorry; I should have tried all the obvious tricks first.  The problem was ultimately resolved after rebooting the system.

**Comment by circuitmike** [comment]
So what fixed it? I'm in the same situation here. I get this error even running as root.
