### ISSUE TITLE
Need data dumps for effects

### ISSUE THREAD

**Issue by noisycat** [MatMoul/g810-led#27]
Task list for data dumps required for full featured deployment

- [ ] Breathing
    - [ ] solved color
    - [ ] solved speed
        - [ ] speed - high
        - [ ] speed - mid
        - [ ] speed - low
- [ ] Fixed Color
    - [ ] solved color
- [ ] Color Cycle
    - [ ] speed
        - [ ] speed - high
        - [ ] speed - mid
        - [ ] speed - low
- [ ] Color Wave
    - [ ] direction
        - [ ]  Horizontal
        - [ ]  Vertical
        - [ ]  Center Out
    - [ ] speed

**Comment by MatMoul** [comment]
New dump here
