### ISSUE TITLE
Matching or compatible device not found

### ISSUE THREAD

**Issue by buxx** [MatMoul/g810-led#274]
Hello, I just installed this program from debian packages. Program can find my keyboard when list, but fail when apply a color :
```
➜  Projets g413-led --list-keyboards
Device: Logitech - G413 Carbon Mechanical Gaming Keyboard
	Vendor ID: 046d
	Product ID: c33a
	Serial Number: 1671306C3832
➜  Projets g413-led -a 00ff00       
Matching or compatible device not found !
```

What should I do ?

**Comment by robtech21** [comment]
This happened to me with my G213 and I was able to fix it quickly. In your case you'd probably want to do:

`g413-led -ds 1671306C3832`

and then try setting a theme

**Comment by elidrissidev** [comment]
Had the same error using Manjaro KDE, running the command `sudo` did the trick for me. Hope it helps someone.

**Comment by robtech21** [comment]
> Had the same error using Manjaro KDE, running the command with `sudo` did the trick for me. Hope it helps someone.

Yes, using sudo also helps.

**Comment by buxx** [comment]
Thanks ! I close the issue.
