### ISSUE TITLE
Group: gkeys

### ISSUE THREAD

**Issue by sebschlicht** [MatMoul/g810-led#28]
According to the [use page](https://github.com/MatMoul/g810-led/wiki/Use) of your wiki, there is no group for the G-keys.
However, on spec I used the group value `gkeys` analogous to `fkeys` to set the colors on my G910 - which surprisingly worked.
It may be just a typo and `keys` should be `gkeys` but that group should definitely be mentioned, as your software supports it.

**Comment by MatMoul** [comment]
sorry wiki need to be updated
gkeys is include in the code

**Comment by sebschlicht** [comment]
Yeah, sorry I found it in the `--list-keys` output a few minutes after I've created this issue. My bad. However, at least it's missing in the docs :)

**Comment by MatMoul** [comment]
wiki and --help is updated
