### ISSUE TITLE
Next project name

### ISSUE THREAD

**Issue by MatMoul** [MatMoul/g810-led#29]
I have maked this project for the logitech G810 keyboard but now, it's compatible with G410, G610 and G910...

It becomes interesting to think if the project name should become more generic.

As examples:
logi-led
logi-rgb
other ?

what do you think ?

**Comment by noisycat** [comment]
not rgb, since the 610s are technically not rgb. :+1: 

:8ball: ...

I'd put in "logi-light"

But we'll need to make sure and list the keyboards that we can deal with - since I know I stumbled onto the project in a very roundabout way...

**Comment by MatMoul** [comment]
@noisycat, You're right, the keyword rgb is not the best ...
I googled "Apex M800" and if this project can be compatible with these keyboards, "logi" is not a good keyword either.

**Comment by noisycat** [comment]
I mean, all it would take is for someone to extend the control software scheme to vendors other than 0x046d 

:-D

But actually, let's go with logi-light - I was curious and looked up what else logi could mean - and apparently its old nordish for literally Fire. Fire Light :+1:

**Comment by MatMoul** [comment]
Other idea :
kbd-led
lkbd-led (l for logitech)
gkbd-led (g for gaming)

**Comment by MatMoul** [comment]
Because this project can not respond to requests for animations, it is necessary to create a daemon that can support this functionality.
For this, I intend to create a new project that work as a daemon and will allow this possibility.
I however need your feedback regarding the name of this next software.

**Comment by MohamadSaada** [comment]
Hi, I'm already working on another project and all files will be up in the next week, It has a gui and a daemon for the effects, I have four effects working already, if you want to check the description at <a href="https://github.com/MohamadSaada/Logitech-G-Series-Keyboard-Software">Logitech G Series Keyboard Software</a>, please let me know what you think.

**Comment by MatMoul** [comment]
@MohamadSaada Interesting, I wait to see your code ...
Deamon is a very hard work and I don't need it...
If you work on it, it's good for me

**Comment by Shulyaka** [comment]
The "LogiLed" seems to be the name that Logitech itself uses in its SDK: http://gaming.logitech.com/sdk/LED_8.87.zip

**Comment by MatMoul** [comment]
@Shulyaka Thanks for the info, it's better to not enter in conflict with Logitech...

**Comment by konserw** [comment]
My proposal is "ledkeyboard" for app and "libledkeyboard" for library - I've used that naming in PR #121 but if it is not acceptable I'll gladly change it to anything else :)

**Comment by lanodan** [comment]
What about a name that would also include mouses and potentially other stuff?

I propose button-leds (not sure about where to put the plural btw)

**Comment by MatMoul** [comment]
@lanodan Thanks for return, but i encouter now a new problem with mouse...
My code handle only one Logitech device and if you have a G keyboard and a G mouse, g810-led can't manage the two devices...

**Comment by dioni21** [comment]
@MatMoul 
> My code handle only one Logitech device and if you have a G keyboard and a G mouse, g810-led can't manage the two devices...

Then you want/need a BIGGER change, where you can specify device paths, vendors, layouts and many other options.

This may not be easy just from a command line and keeping compatibility.  Time to restart from scratch?  This would also make the daemon project easier.
