### ISSUE TITLE
Command line option for Logitech G410

### ISSUE THREAD

**Issue by GHPS** [MatMoul/g810-led#3]
I 'm using g810-led with my Logitech G410 which is basically a smaller version of the G810 with the same RGB Romer-G keys. It was rather easy to get the program working - I just changed the USB product ID (PID) from 331 to 330. This patch works in the C and the Python version of the program.

Perhaps the G410 could be officially supported? Via a command line option to select either G810 or the G410?

**Comment by MatMoul** [comment]
Thank you this info,

I reflect on possible changes according to your return.

**Comment by MatMoul** [comment]
Try the last version.
After make, rename g810-led to g410-led, it should work.

**Comment by GHPS** [comment]
Works perfectly - thanks!
