### ISSUE TITLE
Wrong executable path in systemd service file

### ISSUE THREAD

**Issue by sebschlicht** [MatMoul/g810-led#30]
In the [set profile on boot](https://github.com/MatMoul/g810-led/wiki/Set-profile-on-boot-and-reboot) wiki page when referring to the executable in the `Service` section it is assumed to be located in `/bin`:

    [Service]
    ExecStart=/bin/g810-led -p /etc/g810-led/profile

When the user has followed the installation instructions that are currently present in the wiki, the executable will be located in `/usr/bin`. Thus the section should be changed to:

    [Service]
    ExecStart=/usr/bin/g810-led -p /etc/g810-led/profile

**Comment by sebschlicht** [comment]
This applies to both systemd service files present.

**Comment by MatMoul** [comment]
Thank for return, I just updated the wiki and the systemd/g810-led.service file.
