### ISSUE TITLE
Y and Z keys crossed with QWERTY keyboard ?

### ISSUE THREAD

**Issue by MatMoul** [MatMoul/g810-led#31]
With my QWERTZ keyboard, in the code, the y and z keys don't follow each other values of the constants.
Can anyone confirm that the y and z keys are not crossed with a QWERTY keyboard ?
Test with ; g810-led -k z 00ff00

**Comment by markfullalove** [comment]
Yes, I can confirm that on a QWERTY keyboard the Y and Z are indeed swapped.

**Comment by MatMoul** [comment]
Than you
