### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by alba4k** [MatMoul/g810-led#312]
Hey @MatMoul , I noticed the aur packages for this are currently orphans

Would you mind if I took over them? what packages actually matter?

Was thinking about putting some patches for https://github.com/MatMoul/g810-led/issues/311 in the pkgbuild, not sure if you're still working on this or not

**Comment by BenjaminMoraga** [comment]
What's the future of this package? It's not on the AUR and compile from source requires to include inttypes.h manually.

**Comment by alba4k** [comment]
I took ownership of those for a while and then deleted them as this project is basically abandoned and now, as far as I understand, part of openrgb
