### ISSUE TITLE
Built-in effects on g910

### ISSUE THREAD

**Issue by markfullalove** [MatMoul/g810-led#33]
On the g910 orion spectrum model it is necessary to change data[2] from 0x0d to 0x10 in each of the Keyboard::setFX functions. With this change in place all of the new patterns now work on this model. I'm not sure that 'speed' does anything though.

**Comment by MatMoul** [comment]
I just added the changes as shown.
Can you test the new version?
For speed, it must be set in hex mode (00 to FF).
For tests, between 10 and 90, you should see a difference.

**Comment by markfullalove** [comment]
This is all working perfectly now thank you. 
The speed works fine too ( I don't know why I thought that it didn't ! )

**Comment by MatMoul** [comment]
@markfullalove  Thank you for your work
