### ISSUE TITLE
g610 brown help required

### ISSUE THREAD

**Issue by babhijit** [MatMoul/g810-led#46]
When I tried to set up fx effect using the command:
        g610-led -fx hwave keys ff

The entire keyboard became dark. Thanks in advance for help :)

**Comment by MatMoul** [comment]
Thank for your return...

At this time, -fx is confirmed only on G810 because I don't have other model for test it.

Have you tested with other value than ff?
And for other effects? Do they work?

**Comment by MohamadSaada** [comment]
Hi MatMoul, sorry for hijacking the thread, but there is no other way of contacting you, I've uploaded my code for the GUI under [LogiGSK](https://github.com/MohamadSaada/LogiGSK), if you can check whether it works on your device or not, I would really appreciate it.

**Comment by MatMoul** [comment]
@MohamadSaada I will try this week-end if I found time...

**Comment by CReimer** [comment]
Just to let you know.
All effects work on my g910 just fine.

**Comment by MatMoul** [comment]
@CReimer Thanks for your return

**Comment by MatMoul** [comment]
@babhijit I close this issue because I don't have return... but you can reply me here if you encouter problem

**Comment by jpl81** [comment]
I also have a G610. The hwave, vwave and cwave effects don't work on my g610 irrespective of the value given. The cycle effect works but the value of speed does not seem to make any difference. Other effects (color, breathing) work as they should.

**Comment by MatMoul** [comment]
@jpl81 Thank for your return, but taht is an other issue...
I'm missing time thes days but open a new issue for this case.
