### ISSUE TITLE
Keys with no color after script / profile

### ISSUE THREAD

**Issue by asathoor** [MatMoul/g810-led#49]
When I run a `g810-led -pp < profilefile` some random keys are not colored. I have to repeat once, sometimes twice before all keys are as I want them to. On the fly it's not a big issue, but when I try to color the keys via `rc.local` or similar it's an issue.

**Comment by MatMoul** [comment]
Seem the same problem than the second part of #45

**Comment by MatMoul** [comment]
Do you have the same result with "g810-led -p profilefile" ?

**Comment by asathoor** [comment]
Yes sometimes. However that was yesterday. I'll test out the recent version of the code now.

**Comment by asathoor** [comment]
Yes. The issue is the same: Tried some `g810-led -p all_blue` etc from the sample files. The problem is the same. Some random keys are not colored. Right now my keybard is a mixture of red and green keys afer a `... all_green` followed by a `all_red`.

* OS: Linux 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MatMoul** [comment]
Sorry, I can not reproduce but it's a bug...
Try the solution of @CReimer on issue #45

**Comment by MatMoul** [comment]
@asathoor Seem to be fixxed in the last version...
Can you confirm ?

**Comment by MatMoul** [comment]
I have two confirmations, I close the bug.
If bug persist, I will reopen it

**Comment by asathoor** [comment]
Perhaps it's a "freak of nature". But on my system it's still a problem.

**Comment by asathoor** [comment]
After an update a minute ago everything works fine. I tried to run the script from rc.local - but if the Ubuntu GUI for upstart programs is used everything works fine. So I guess that's the proper way to run g810-led on Ubuntu.

**Comment by asathoor** [comment]
Now everything is ok. I changed the script from rc.local to the standard Ubuntu add programs on upstart. Now everything works as a charm.

**Comment by MatMoul** [comment]
Thank's for your return
It's cool to hear that..
