### ISSUE TITLE
Key Press / Fade

### ISSUE THREAD

**Issue by fireAnon** [MatMoul/g810-led#50]
Hello! Just wanted to say thank you so much for uploading this, very simple easy to use, I love it. Was playing around though and found im having a hard time getting a key press then fade back to original color effect. Logitec offers: _**Key Press** — The keys change color when you press them. Use the color selection wheel to choose a preset color or customize your own. You can also set a background color for the entire keyboard. Use the slider to set the rate at which the color fades back to the background color._

I was curious If you had any Ideas on how to make this work, also I found I cannot find a way to set a color to my numberpad_enter key, I've tried _g810-led -k num_enter 00ffff_ and _g810-led -k enter 00ffff_ but neither seem to work for me.

***edit*** I read something in a earlier closed post about the key press needing the gaming software to work? were you and noisycat suggesting It could work within a vm if I run the software in the vm>?

**Comment by MatMoul** [comment]
Try numenter : g810-led -k numenter 00ffff
You can find all keys with g810-led --help-keys

**Comment by fireAnon** [comment]
that worked, yea I see it now sorry I missed that, as for the key press, is that not possible right now? Thank you for the quick response @MatMoul

**Comment by MatMoul** [comment]
Indeed for the "KeyPress" it is not possible for the moment ...
The future evolutions are described in the TODO.md file
[https://github.com/MatMoul/g810-led/blob/master/TODO.md](https://github.com/MatMoul/g810-led/blob/master/TODO.md)
