### ISSUE TITLE
G410 Logo

### ISSUE THREAD

**Issue by Landrovan** [MatMoul/g810-led#53]
In the help-keys of the G410, they talk of Logo. And that it need confirmation. I have the G410, and there is no logo that have a light. Even the logitech soft, you can't do anything with the logo.
P.S. not sure if an issue is the right place to ask to remove this, but I didn't find a better place.

**Comment by MatMoul** [comment]
Thanks for your return, this is the right place for that...
I tag to enhancement for futur version

**Comment by MatMoul** [comment]
New version here
