### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by Thanosar** [MatMoul/g810-led#54]
Hi, after "sudo make install" displays:

cp: αδυναμία αντικατάστασης του καταλόγου '/usr/bin/g810-led' με μη κατάλογο
makefile:29: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by MatMoul** [comment]
It seem your /usr/bin/g810-led is a directory, not ?
Not sure why you have a g810-led directory in your /usr/bin but it's not my software...
you can rename or delete it :
`sudo mv /usr/bin/g810-led /usr/bin/g810-led.bak`
`sudo rm -R /usr/bin/g810-led`
and then
`sudo make install`

**Comment by Thanosar** [comment]
Ok. Problem Solver!! Thank you very much..
