### ISSUE TITLE
Segregate installed components

### ISSUE THREAD

**Issue by pearsonk** [MatMoul/g810-led#66]
Currently the install target provides the g810-led binary with symlinks, systemd services, and samples. Makefile can be segregated to allow for more fine-grained control over what gets installed, to allow packaging things separately. Furthermore, there is inconsistent use of DESTDIR that can be applied more completely to allow staging all appropriate files into distributable packages.

**Comment by MatMoul** [comment]
At this time, I use make install to install and make setup to make package for arch-linux.
Look at [https://github.com/MatMoul/aur/tree/master/g810-led-git](https://github.com/MatMoul/aur/tree/master/g810-led-git)
If you have a best solution, you can expose here and make a PR if it's a best solution
