### ISSUE TITLE
Asterisk symbol not working on Nordic keyboards 

### ISSUE THREAD

**Issue by zone31** [MatMoul/g810-led#67]
When using single key operations (-k) on my g810 i can set all other keys, except for the asterisk(*) key on my keyboard. When setting the locale to English, the key becomes backslash(\\). When using the key group, the color changes correctly. I have tried g810-led -k backslash ff00ff , which did not change it.
I am using the (0x46d, 0xc337) model g810.
I have added images of my keyboard in english locale, and Nordic(Danish) locale. 
The reported keycode is 43 decimal.
![image](https://cloud.githubusercontent.com/assets/2137304/24795796/e6a44550-1b8a-11e7-9411-d4400fd67d57.png)

![image](https://cloud.githubusercontent.com/assets/2137304/24795835/027fe0fe-1b8b-11e7-9459-67e768c6730d.png)

**Comment by MatMoul** [comment]
Try with intl_backslash
or test all possibility in g810-led --help-keys (in Group keys)

**Comment by zone31** [comment]
got it to work, it is called "dollar" in the project. 
Thanks for the help :)
