### ISSUE TITLE
Daemon with scenarios

### ISSUE THREAD

**Issue by MatMoul** [MatMoul/g810-led#78]
I just pushed a new branch named daemon that support scenario file.
Scenario file can contain all commands available in profile file and also :
* w time : wait time in millisecond
* p filename : load a profile

To launch it, call :
g810-led --daemon scenarioFileName
To kill it, call :
kill -2 pid (pid is returned when you launch daemon)

Returns are welcome

**Comment by MatMoul** [comment]
Now I have tested scenario0 but it don't work very well when you use your keyboard.
I have added a k2000 scenario who work well.

Clarification : This branch is not intended to be merged as is. But for testing this solution.

Small note for scenarioFileName: Because it's a daemon, absolute paths must be used.

**Comment by MatMoul** [comment]
Now scenario0 work well.
Need tester for returns.

**Comment by PFCKrutonium** [comment]
Okay, so I built this branch, and ran
`./bin/g810-led --daemon ~/sample_scenarios/k2000 ` - Which seems to have done nothing?

**Comment by MatMoul** [comment]
Thank you for your return.

At this time only the p and w commands are available.

A first possibility is to use a second script to generate the scenario in a cron or other trigger.
When daemon is launched, you can update the scenario file without restarting the daemon.
As exemplle, you can test by updating waittime k2000

I also provided a unit that copy the scenario file in /tmp/g810-led-scenario
When the unit is started just update this file to change the effect.

Now I think about how I can handle more possibilities (calling bash or python script) but the dilemma is the security.
