### ISSUE TITLE
gpro loses key settings

### ISSUE THREAD

**Issue by lleukkun** [MatMoul/g810-led#80]
My gpro is occasionally switching key colors or turning them off completely. Sometimes just one, but just had most of the regular keys go dark. Re-running gpro-led fixes this, but perhaps there's some power management thing kicking in? I will try to investigate this more.

**Comment by MatMoul** [comment]
It's possible that this bug is the same that #81

**Comment by MatMoul** [comment]
@lleukkun I just pushed a new branch named "bug_sometime_wrong_key_color" with an updated sendDataInternal function.
Try with this branch...

**Comment by MatMoul** [comment]
Branch "bug_sometime_wrong_key_color" is now merged to master.
Just install the last version

**Comment by lleukkun** [comment]
I can't trigger this anymore, running currently with the latest. If it comes back I'll reopen.

**Comment by lleukkun** [comment]
And it happened again about 5 minutes after closing this ticket, running version 0.2.5 (commit 99447196561c5e083e7bd1f2fda69d8cebdab4fd). Reopening.

**Comment by FruityFaiz** [comment]
For now I'd suggest you set your colours in Windows, if I remember right, the GPRO has on board memory so it should save it.

**Comment by MatMoul** [comment]
@FruityFaiz Thanks for your return.

@lleukkun It can be good to test setting keys with windows software and see if your keyboard lost color in linux after a certain time.

**Comment by lleukkun** [comment]
gpro may have memory but it reverts to the same default effect after reboot so doing things in windows doesn't really make any difference. We should probably just sniff what the windows software is doing over usb and see if there's something that stands out.

**Comment by MatMoul** [comment]
@lleukkun What the state of this issue ?
No news, good news ?

**Comment by MatMoul** [comment]
@lleukkun 2 month without reply, reopen issue if needed
