### ISSUE TITLE
Left Alt is Green?

### ISSUE THREAD

**Issue by PFCKrutonium** [MatMoul/g810-led#81]
```
g logo 000096       # Blue
g indicators ffffff # White
g multimedia 009600 # Green
g fkeys ff7700      # Orange
g modifiers ff7700  # Orange
g arrows 0000ff     # Red
g numeric 00ff00    # Green
g functions ffffff  # White
g keys ff00ff       # Purple
g gkeys ffffff      # White
k tilde ff0000      # Red
k W 0000ff          # Blue {
k A 0000ff
k S 0000ff
k D 0000ff          # }
k 1 ff0000          # Red {
k 2 ff0000
k 3 ff0000
k 4 ff0000
k 5 ff0000
k 6 ff0000
k 7 ff0000
k 8 ff0000
k 9 ff0000
k 0 ff0000          # }
c                   # Commit changes
```
This is the profile I am using right now. It all works (mostly) correctly - somtimes some keys don't change (my F Keys didn't turn on last reboot), but my left alt is consistently green. Any ideas what's up, or is this a bug in the software?

![greenalt](https://cloud.githubusercontent.com/assets/3945538/26136959/1d4988c4-3a8d-11e7-8090-c93c6b02f896.jpg)

G810.

**Comment by PFCKrutonium** [comment]
Temp Fix:
`k alt_left ff7700`

**Comment by MatMoul** [comment]
Very strange, do you use the last version?

**Comment by PFCKrutonium** [comment]
Yep, in fact, I am using the Arch (AUR) g810-led-git package - which is build from the repo.

**Comment by MatMoul** [comment]
At this time, I can not reproduce, need more investigation...
I try to test your profile in the next few days

**Comment by MatMoul** [comment]
I also encounter some problem with your profile.
Now, I only have to search :(

**Comment by MatMoul** [comment]
After small tests, I suggest to add a commit (c) after line 10 (g gkeys ffffff      # White).
Set all group, commit, set keys and commit.
If it work, I need to update code for handle this case.

**Comment by PFCKrutonium** [comment]
Okay, giving this a shot.

**Comment by PFCKrutonium** [comment]
My F keys still do not light up by default, and now my menu key (the key to the right of the right Windows key) has not lit up either.

**Comment by PFCKrutonium** [comment]
Current Profile as of now:
```
# Sample profile by groups keys

g logo 000096       # Blue
g indicators ffffff # White
g multimedia 009600 # Green
g fkeys ff7700      # Orange
g modifiers ff7700  # Orange
g arrows 0000ff     # Red
g numeric 00ff00    # Green
g functions ffffff  # White
g keys ff00ff       # Purple
g gkeys ffffff      # White
c                   # Commit
k tilde ff0000      # Red
k W 0000ff          # Blue {
k A 0000ff
k S 0000ff
k D 0000ff          # }
k 1 ff0000          # Red {
k 2 ff0000
k 3 ff0000
k 4 ff0000
k 5 ff0000
k 6 ff0000
k 7 ff0000
k 8 ff0000
k 9 ff0000
k 0 ff0000          # }
# k alt_left ff7700   # BUG!!! Has to be manually set!
c                   # Commit changes
```

**Comment by MatMoul** [comment]
No luck...
You can try temporarily with libusb. (reinstall the package and edit the PKGBUIL)
Concerning your profile, it is correct for me.
You can also remove the intermediate commit (c) that I suggested, it is useless.
I investigate...

**Comment by MatMoul** [comment]
I have pushed a new branch named "bug_sometime_wrong_key_color" that contain a fix.
Can you test ?

**Comment by PFCKrutonium** [comment]
Will give that a shot

**Comment by PFCKrutonium** [comment]
Okay, so using that branch without rebooting (Installing some stuff that takes a while, will update afterwards) Appears to have worked, except that my fkeys remain turned off for some reason.

**Comment by MatMoul** [comment]
fkeys work well for me...
Try to unplug and replug your keyboard.

**Comment by PFCKrutonium** [comment]
Nope, It visibly reset but didn't correct the F keys.

**Comment by MatMoul** [comment]
Just to be sure, when you have installed the branch "bug_sometime_wrong_key_color" you have only replaced the line 19 in PKGBUILD with :
source=("git://github.com/MatMoul/${_appname}.git#branch=bug_sometime_wrong_key_color")

**Comment by PFCKrutonium** [comment]
I didn't use the pkgbuild, I did it manually
```
[krutonium@krutonium-desktop g810-led]$ git status
On branch bug_sometime_wrong_key_color
Your branch is ahead of 'origin/bug_sometime_wrong_key_color' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
[krutonium@krutonium-desktop g810-led]$
```
I ran `make bin` and copied the resulting executable to `/usr/bin/g810-led`

**Comment by MatMoul** [comment]
And what happens when you make a
g810-led -k f1 ff0000

**Comment by PFCKrutonium** [comment]
That also worked.

**Comment by MatMoul** [comment]
Your build method is ok
But is it normal that your branch is ahead of ... by 1 commit ?
And what appens when you make a 
g810-led g fkeys ff7700

**Comment by PFCKrutonium** [comment]
Honestly I don't know why it says that, I did a `git reset --hard` and it still gives me that message.

```
[krutonium@krutonium-desktop g810-led]$ g810-led g fkeys ff7700
```
Outputs usage/help.

**Comment by MatMoul** [comment]
sorry...
g810-led -g fkeys ff7700

**Comment by PFCKrutonium** [comment]
Yep, that worked correctly.

**Comment by MatMoul** [comment]
Very strange.... the -g fkeys is the same function that is used in profile file.
No idea for now.
I will make a new release with the last changes and we will investigate from this new base

**Comment by PFCKrutonium** [comment]
Okay. Should I make a new issue for the F keys?

**Comment by MatMoul** [comment]
Yes it will be good

**Comment by PFCKrutonium** [comment]
Will do.

**Comment by MatMoul** [comment]
Thank for your work, you can make a PR with your profile in sample...
It's a good profile for debug the code

**Comment by PFCKrutonium** [comment]
Sure.
