### ISSUE TITLE
Procedural vs object hierarchical organization

### ISSUE THREAD

**Issue by pearsonk** [MatMoul/g810-led#82]
There are talks to add support for non-Logitech keyboards, and as the number of supported systems in the current procedural implementation is causing a lot of if/switch parsing based on the KeyboardModel which will only get more complex as the list grows and they types of keyboards and protocols grows.

An alternative approach would be to disaggregate Keyboard.cpp implementations into separate classes, with protocol implementation in an intermediary, and model-specific implementation in a model-specific class.

I believe most of this work could be done without much disruption to the library API. It would be quite an overhaul, though.

**Comment by pearsonk** [comment]
Some additional complexity comes with any intent to support more than Logitech keyboards. While some functions such as setting key color and intensity are fairly universal, power-on effects and native effects are likely not as common, therefore not best to be exposed at the highest class in the hierarchy. One way around this could be dynamic_cast checks for implementers, or logic in the implementer based on vendor ID, especially if there is a vendor-specific intermediary class that exposes vendor-specific implementations such as native effects capabilities.

**Comment by pearsonk** [comment]
![ledkb](https://cloud.githubusercontent.com/assets/7871802/26168188/39ecd542-3b07-11e7-91b1-35dbb9f54814.png)

Here's an illustration of what I was talking about.

**Comment by MatMoul** [comment]
This was one of my idea but I didn't have time to do it.
I think it's good direction to be followed for the next step.

**Comment by aik18** [comment]
I've had a logitech G510s and G15 keyboard, and I wrote a c++ userspace program to control the leds. Full control over the G510 and G13 keyboards works as well. I could provide the code.

**Comment by MatMoul** [comment]
@aik18 Thank you for the proposal, I'm very interrested.

**Comment by MatMoul** [comment]
Closing because expired issue
