### ISSUE TITLE
G810 UK Layout

### ISSUE THREAD

**Issue by FruityFaiz** [MatMoul/g810-led#92]
Hey, for some reason I cannot get it to work with my G810. When I execute `g810-led --list-keyboards`, it lists my keyboard but when executing anything else I get 

> Matching or compatible device not found !

When I installed it, it also changed my keyboard's colours so it seems to be working fine. 

I'm on Arch Linux, if you need any dumps etc just let me know.

Thank you!

EDIT: When executing: `g810-led -ds 0B64289R3488 -dv 046d -dp c337 -tuk 1 -k logo ff0000`
It returns false at Keyboard.cpp:196:` if (m_hidHandle == 0) return false`

**Comment by MatMoul** [comment]
If the --list-keyboard command work and when your have installed g810-led your keys have changed color, your keyboard are supported.
Do you have tryed g810-led -a ff0000?

**Comment by FruityFaiz** [comment]
Hey, same problem when executing `g810-led -a ff0000`.
It seems to detect the keyboard(right IDs) when Keyboard::open is called but hid_open() seems to be returning a NULL pointer for some reason.

**Comment by MatMoul** [comment]
Very strange, this is the same internal code that is called after installation and it works (dump not required).

Need more investigation...
Without destroying your computer, try with a clean install of ArchLinux on a second disk or a vm.
If it works, you must have a software that enter in conflict with g810-led.

**Comment by FruityFaiz** [comment]
Seems to be my system or hidapi, running the code beneath prints

> Failed to open device.

`#include <iostream>
#include <hidapi/hidapi.h>

int main()
{
	if (hid_init() < 0)
		std::cout << "Failed to initialise." << std::endl;	

	auto dev = hid_open(1133, 49975, NULL);

	if (dev == 0) {
		hid_exit();
		std::cout << "Failed to open device." << std::endl;
	}

	return 0;
}
`

I will get back to you with what I find out. Thanks!

**Comment by pearsonk** [comment]
Try running your code as root (difference between the installed udev base/profile and normal user). This may indicate a permissions or hidapi problem.

You can also get more information if you add prior to your hid_exit call of your test application:
`std::wcout << hid_error(dev) << std::endl;`
Requires including wstring.

**Comment by FruityFaiz** [comment]
Oh gosh! Running as root worked. Thanks. 

And extra information isn't printed when adding that just before the exit call.

**Comment by MatMoul** [comment]
Very strange, the udev rules contain MODE="666" that allow all users to use it.
Do you use the aur package or make and make install?

**Comment by FruityFaiz** [comment]
I used both, same problem.

**Comment by MatMoul** [comment]
Ok, I recommand you to use the aur package, with it, you receive updates...

It seem that is a udev problem, but normally, it is include in systemd.

**Comment by FruityFaiz** [comment]
Just started working after a restart...
