### ISSUE TITLE
G810 - Rainbow affect G logo

### ISSUE THREAD

**Issue by FruityFaiz** [MatMoul/g810-led#93]
Hey, I was wondering if it would be possible to have the G logo sync with the rainbow affect. WIth the current logitech gaming software, the G logo also changes colours.

Using the following command: `g810-led -fx hwave keys 0a` does not affect the G logo or indicators.

Thank you!

**Comment by MatMoul** [comment]
I have tried to do it, but I can't sync the logo animation with the keys animation...
You can try by calling g810-led -fx cycle logo 0a... (this is the method extracted from the dump)
Even if you change the speed, the logo animation loses sync...

**Comment by FruityFaiz** [comment]
It's fine, would be nice but not a problem much, I can live.

If you ever do decide to look into it, just to let you know the colour changes from red to green rapid, instead of going yellow then green. I think that might be your issue.

**Comment by MatMoul** [comment]
I would try to look into it if I have time.
But for now, I work on other features that is a priority for me.

**Comment by FruityFaiz** [comment]
Ye no problem doesn't matter. Just let me know if you get it fixed :+1:

**Comment by A1rPun** [comment]
I'm very happy with this command which I extracted from this issue 😄 
```
g810-led -fx hwave keys ff && g810-led -fx cycle logo ff
```
The desync isn't that terrible

**Comment by MatMoul** [comment]
Can I close this issue ?

**Comment by A1rPun** [comment]
@MatMoul I would love this feature being implemented because I always use `g810-led` in combination with the rainbow effect! I assume you looked into this so if it is not possible there is no choice other than closing this issue.

**Comment by MatMoul** [comment]
Thank's for your return and sorry that I can make anything more
